# @base_url = https://tool.comdev.my.id/api/
@base_url = http://localhost/tool/api/mobile/
@token = satuduatiga


### POST Request ###
POST {{base_url}}login_staff
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nik": "007288/2019",
  "password": "1sampai10"
}
### ####
GET {{base_url}}data_laporan
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nik": "007288/2019",
  "password": "1sampai10"
}
