# @base_url = https://tool.comdev.my.id/api/
@base_url = http://localhost/tool/api/mobile/
@token = satuduatiga


### POST Request ###
POST {{base_url}}login_staff
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nik": "007288/2019",
  "password": "1sampai10"
}
### ####
POST {{base_url}}data_laporan
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nik": "007288/2019",
  "cabang": "BARRU",
  "minggu": "1",
  "bulan": "2",
  "tahun": "2024",
}
### ####
GET {{base_url}}laporan_cabang?cabang=12&id_staff=13
Content-Type: application/json
Authorization: Bearer {{token}}
### ####
DELETE {{base_url}}hapus_laporan?id=20
Content-Type: application/json
Authorization: Bearer {{token}}

####CEK PROGRES CABANG ###
POST {{base_url}}cek_progress_cabang
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "cabang": "PANGKEP",
  "minggu": "3",
  "bulan": "1",
  "tahun": "2024",
}



### ####
GET {{base_url}}test_fcm?cabang=12&id_staff=13
Content-Type: application/json
Authorization: Bearer {{token}}


###SCAN###
GET {{base_url}}scan?url=dsdsd
Content-Type: application/json
Authorization: Bearer {{token}}


####CEK PROGRES CABANG ###
GET {{base_url}}test_fcm
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "PANGKEP",
  "body": "3",
  "token": "d3UN6zazTEWT609CnApdQU:APA91bGpCrWbUCAklwSrqpKwD0s0wP3u9SAtMdDncftP1V8Z1e9O5JK9TYalyLi8CwXWJWHdP0Uqkwjv2r7M6Soqg_IBP0n5zpkJd1ccjz0U0oMixPnc7U6OY-4ynwckYn-ctoeeWhpF",
  "data": "2024",
}
